import xarray as xr

adicomp = xr.open_dataset('/nobackup_1/users/walj/racmo24/Threehourly/adicomp.KNMI-1960.KEXT12.RACMO24p1v7_FINAL_enbud_fix.3H.nc')
# convect = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/convect.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# horadv = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/horadv.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lcbotdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lcbotdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lcbotup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lcbotup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lcnet = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lcnet.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lctopdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lctopdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lctopup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lctopup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lscld = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lscld.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lwbotdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lwbotdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lwbotup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lwbotup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lwnet = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lwnet.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lwtopdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lwtopdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# lwtopup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/lwtopup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # mlmid = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/mlmid.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # mltop = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/mltop.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # radtot = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/radtot.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # scbotdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/scbotdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # scbotup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/scbotup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # scnet = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/scnet.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # sctopdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/sctopdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # sctopup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/sctopup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# swbotdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/swbotdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# swbotup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/swbotup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# swnet = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/swnet.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# swtopdn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/swtopdn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# swtopup = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/swtopup.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# templ1 = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/templ1.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # totdyn = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/totdyn.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # totphys = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/totphys.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # totphys2 = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/totphys2.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# tottend = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/tottend.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# udtdx = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/udtdx.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # vdffric = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/vdffric.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # vdfphase = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/vdfphase.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # vdfsens = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/vdfsens.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # vdftot = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/vdftot.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# vdtdy = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/vdtdy.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# # vertadv = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/vertadv.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# numbnd = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/numbnd.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')
# numdif = xr.open_dataset('/nobackup/users/walj/enbud_aerosol/numdif.KNMI-1960.KEXT12.RACMO24p1v7_enbud.3H.nc')

# #%%

# test = xr.open_dataset('/nobackup/users/walj/enbud_combined/tas_monthlyA_KEXT12_RACMO24p1v7_enbudrun_start_198001_198412.nc')

