import xarray as xr

adicomp = xr.open_dataset('/nobackup/users/walj/enbudtemp/adicomp.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
convect = xr.open_dataset('/nobackup/users/walj/enbudtemp/convect.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
horadv = xr.open_dataset('/nobackup/users/walj/enbudtemp/horadv.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lcbotdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/lcbotdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lcbotup = xr.open_dataset('/nobackup/users/walj/enbudtemp/lcbotup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lcnet = xr.open_dataset('/nobackup/users/walj/enbudtemp/lcnet.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lctopdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/lctopdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lctopup = xr.open_dataset('/nobackup/users/walj/enbudtemp/lctopup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lscld = xr.open_dataset('/nobackup/users/walj/enbudtemp/lscld.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lwbotdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/lwbotdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lwbotup = xr.open_dataset('/nobackup/users/walj/enbudtemp/lwbotup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lwnet = xr.open_dataset('/nobackup/users/walj/enbudtemp/lwnet.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lwtopdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/lwtopdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
lwtopup = xr.open_dataset('/nobackup/users/walj/enbudtemp/lwtopup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
mlmid = xr.open_dataset('/nobackup/users/walj/enbudtemp/mlmid.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
mltop = xr.open_dataset('/nobackup/users/walj/enbudtemp/mltop.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
radtot = xr.open_dataset('/nobackup/users/walj/enbudtemp/radtot.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
scbotdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/scbotdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
scbotup = xr.open_dataset('/nobackup/users/walj/enbudtemp/scbotup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
scnet = xr.open_dataset('/nobackup/users/walj/enbudtemp/scnet.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
sctopdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/sctopdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
sctopup = xr.open_dataset('/nobackup/users/walj/enbudtemp/sctopup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
swbotdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/swbotdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
swbotup = xr.open_dataset('/nobackup/users/walj/enbudtemp/swbotup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
swnet = xr.open_dataset('/nobackup/users/walj/enbudtemp/swnet.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
swtopdn = xr.open_dataset('/nobackup/users/walj/enbudtemp/swtopdn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
swtopup = xr.open_dataset('/nobackup/users/walj/enbudtemp/swtopup.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
templ1 = xr.open_dataset('/nobackup/users/walj/enbudtemp/templ1.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
totdyn = xr.open_dataset('/nobackup/users/walj/enbudtemp/totdyn.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
totphys = xr.open_dataset('/nobackup/users/walj/enbudtemp/totphys.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
totphys2 = xr.open_dataset('/nobackup/users/walj/enbudtemp/totphys2.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
tottend = xr.open_dataset('/nobackup/users/walj/enbudtemp/tottend.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
udtdx = xr.open_dataset('/nobackup/users/walj/enbudtemp/udtdx.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
udtdy = xr.open_dataset('/nobackup/users/walj/enbudtemp/udtdy.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vdffric = xr.open_dataset('/nobackup/users/walj/enbudtemp/vdffric.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vdfphase = xr.open_dataset('/nobackup/users/walj/enbudtemp/vdfphase.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vdfsens = xr.open_dataset('/nobackup/users/walj/enbudtemp/vdfsens.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vdftot = xr.open_dataset('/nobackup/users/walj/enbudtemp/vdftot.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vdtdx = xr.open_dataset('/nobackup/users/walj/enbudtemp/vdtdx.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vdtdy = xr.open_dataset('/nobackup/users/walj/enbudtemp/vdtdy.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')
vertadv = xr.open_dataset('/nobackup/users/walj/enbudtemp/vertadv.KNMI-1950.KEXT12.RACMO2.4p1_v5_enbudtemp.3H.nc')


#%%

